//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSembako.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/ServiceSembako")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jmlPesananField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaPembeliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalHargaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOrder {
            get {
                return this.IdOrderField;
            }
            set {
                if ((this.IdOrderField.Equals(value) != true)) {
                    this.IdOrderField = value;
                    this.RaisePropertyChanged("IdOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat {
            get {
                return this.alamatField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatField, value) != true)) {
                    this.alamatField = value;
                    this.RaisePropertyChanged("alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jmlPesanan {
            get {
                return this.jmlPesananField;
            }
            set {
                if ((this.jmlPesananField.Equals(value) != true)) {
                    this.jmlPesananField = value;
                    this.RaisePropertyChanged("jmlPesanan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string namaPembeli {
            get {
                return this.namaPembeliField;
            }
            set {
                if ((object.ReferenceEquals(this.namaPembeliField, value) != true)) {
                    this.namaPembeliField = value;
                    this.RaisePropertyChanged("namaPembeli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string namaProduct {
            get {
                return this.namaProductField;
            }
            set {
                if ((object.ReferenceEquals(this.namaProductField, value) != true)) {
                    this.namaProductField = value;
                    this.RaisePropertyChanged("namaProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalHarga {
            get {
                return this.totalHargaField;
            }
            set {
                if ((this.totalHargaField.Equals(value) != true)) {
                    this.totalHargaField = value;
                    this.RaisePropertyChanged("totalHarga");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ServiceSembako")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deskripsiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int hargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stokField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduct {
            get {
                return this.IdProductField;
            }
            set {
                if ((this.IdProductField.Equals(value) != true)) {
                    this.IdProductField = value;
                    this.RaisePropertyChanged("IdProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deskripsi {
            get {
                return this.deskripsiField;
            }
            set {
                if ((object.ReferenceEquals(this.deskripsiField, value) != true)) {
                    this.deskripsiField = value;
                    this.RaisePropertyChanged("deskripsi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int harga {
            get {
                return this.hargaField;
            }
            set {
                if ((this.hargaField.Equals(value) != true)) {
                    this.hargaField = value;
                    this.RaisePropertyChanged("harga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string namaProduct {
            get {
                return this.namaProductField;
            }
            set {
                if ((object.ReferenceEquals(this.namaProductField, value) != true)) {
                    this.namaProductField = value;
                    this.RaisePropertyChanged("namaProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stok {
            get {
                return this.stokField;
            }
            set {
                if ((this.stokField.Equals(value) != true)) {
                    this.stokField = value;
                    this.RaisePropertyChanged("stok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/order", ReplyAction="http://tempuri.org/IService1/orderResponse")]
        string order(int IdOrder, string namaPembeli, string alamat, int jmlPesanan, int totalHarga, int IdProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/order", ReplyAction="http://tempuri.org/IService1/orderResponse")]
        System.Threading.Tasks.Task<string> orderAsync(int IdOrder, string namaPembeli, string alamat, int jmlPesanan, int totalHarga, int IdProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/product", ReplyAction="http://tempuri.org/IService1/productResponse")]
        string product(int IdProduct, string namaProduct, int harga, int stok, string deskripsi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/product", ReplyAction="http://tempuri.org/IService1/productResponse")]
        System.Threading.Tasks.Task<string> productAsync(int IdProduct, string namaProduct, int harga, int stok, string deskripsi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders", ReplyAction="http://tempuri.org/IService1/OrdersResponse")]
        ClientSembako.ServiceReference1.Order[] Orders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders", ReplyAction="http://tempuri.org/IService1/OrdersResponse")]
        System.Threading.Tasks.Task<ClientSembako.ServiceReference1.Order[]> OrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Products", ReplyAction="http://tempuri.org/IService1/ProductsResponse")]
        ClientSembako.ServiceReference1.Product[] Products();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Products", ReplyAction="http://tempuri.org/IService1/ProductsResponse")]
        System.Threading.Tasks.Task<ClientSembako.ServiceReference1.Product[]> ProductsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientSembako.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientSembako.ServiceReference1.IService1>, ClientSembako.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string order(int IdOrder, string namaPembeli, string alamat, int jmlPesanan, int totalHarga, int IdProduct) {
            return base.Channel.order(IdOrder, namaPembeli, alamat, jmlPesanan, totalHarga, IdProduct);
        }
        
        public System.Threading.Tasks.Task<string> orderAsync(int IdOrder, string namaPembeli, string alamat, int jmlPesanan, int totalHarga, int IdProduct) {
            return base.Channel.orderAsync(IdOrder, namaPembeli, alamat, jmlPesanan, totalHarga, IdProduct);
        }
        
        public string product(int IdProduct, string namaProduct, int harga, int stok, string deskripsi) {
            return base.Channel.product(IdProduct, namaProduct, harga, stok, deskripsi);
        }
        
        public System.Threading.Tasks.Task<string> productAsync(int IdProduct, string namaProduct, int harga, int stok, string deskripsi) {
            return base.Channel.productAsync(IdProduct, namaProduct, harga, stok, deskripsi);
        }
        
        public ClientSembako.ServiceReference1.Order[] Orders() {
            return base.Channel.Orders();
        }
        
        public System.Threading.Tasks.Task<ClientSembako.ServiceReference1.Order[]> OrdersAsync() {
            return base.Channel.OrdersAsync();
        }
        
        public ClientSembako.ServiceReference1.Product[] Products() {
            return base.Channel.Products();
        }
        
        public System.Threading.Tasks.Task<ClientSembako.ServiceReference1.Product[]> ProductsAsync() {
            return base.Channel.ProductsAsync();
        }
    }
}
